language: python

python:
    - "3.8"
env:
    - SECRET_KEY='TEST'
services:
   - SQLite "3.21"
install:
    - pip install -r core/requirements.txt

script:
    - cd core
    - python -m coverage run manage.py test authentication && coverage report && coverage html
after_success:
    - codecov
