language: python

python:
    - "3.8"
env:
    - SECRET_KEY='TEST'
services:
   - postgresql
install:
    - pip install -r core/requirements.txt

script:
    -  python -m coverage run core/manage.py test core/authentication && coverage report && coverage html
after_success:
    - codecov
