language: python

python:
    - "3.8"
env:
    - SECRET_KEY='TEST'
services:
   - postgresql
install:
    - pip install -r core/requirements.txt

script:
    -  coverage run --source='authentication' core/manage.py test && coverage report && coverage html
after_success:
    - codecov
