version: '3.9'

services:
  apps:
    build: 
      context:  .
    restart: always
    volumes:
      - static-data:/vol/web
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:16beta2-bullseye
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - apps
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static
  
volumes:
  postgres-data:
  static-data: