version: '3.9'

services:
  apps:
    build: 
      context: .
    command: >
      sh -c "python3 manage.py wait_for_db &&
              python3 manage.py makemigrations &&
              python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:5000"
    ports:
      - 5000:5000
    volumes:
      - ./core:/core
      - ./data/web:/vol/web
    env_file:
      - core/core/.env
    depends_on:
      - db
  
  db:
    image: postgres:16beta2-bullseye
    env_file:
      - core/core/.env
