# Generated by Django 4.2.3 on 2023-07-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name_plural': 'User preferences'},
        ),
    ]
